### ISSUE TITLE
Consider using modules where possible

### ISSUE THREAD

**Issue by robertdebock** [d4gh0s7/postgres_dump#19]
I think there are some places where you can use modules instead of `command` or `shell` like:

```
    - name: Set up the temporary user
      command: psql --command="ALTER USER {{ random_username.stdout }} WITH PASSWORD '{{ random_string.stdout }}';"
      no_log: Yes
```

Have a look at [this list of postgres modules](https://docs.ansible.com/ansible/2.4/list_of_database_modules.html)

By the way, I really like the creation and deletion of a temporary user.

**Comment by d4gh0s7** [comment]
That's a good suggestion.
Unfortunately, the ansilbe modules for postgresql bring a couple of pitfalls in a few scenarios (depending on the target system's hardening level).

I included **[postgresql_user](https://docs.ansible.com/ansible/2.4/postgresql_user_module.html)**  in order to address the temporary user creation/deletion. Eventually I decided not to include it, at least for now, and to adopt the `command` path. 

It requires further testing/considerations, for instance:
- Check if `psycopg2` is installed
- If not, make it available (?) (could be undesirable, along with `pip`, though I had the same issue with the **expect** module)
- Before making it available, modify the `umask` when the systems are (very) hardened (on my test machine the `umask` is forced to `077`), otherwise the module might not be correctly available.
