### ISSUE TITLE
Add check_mode to shell/command tasks that don't change anything.

### ISSUE THREAD

**Issue by robertdebock** [d4gh0s7/postgres_dump#36]
You can add "check_mode: yes" to tasks that are shell/command/raw, instructing Ansible to run the task anyway, even though it's running in check_mode. (-C).

This allows consumers to run your role in check_mode.

Also see [the docs](https://docs.ansible.com/ansible/latest/reference_appendices/playbooks_keywords.html)

**Comment by d4gh0s7** [comment]
The correct parameter is check_mode: No - in order to instruct ansible to execute the shell/command/raw tasks even when check mode is flagged. Though, to have a full "check mode" that doesn't fail, I need to create some mock tests/tasks on postgres for what concerns the provisioning of the temporary user, cause these are write operations.

**Comment by robertdebock** [comment]
I think you're starting to hit the limitations of Ansible; its interface is designed to be simple.

Maybe you do need to write modules, in order to not use shell/command/raw.

You can also [distribute files to systems to generate facts](https://medium.com/@jezhalford/ansible-custom-facts-1e1d1bf65db8).
